### ISSUE TITLE
worked example from 2015 paper: what's the meaning of alpha, sigma and theta?

### ISSUE THREAD

**Issue by r03ert0** [JClavel/mvMORPH#9]
Hello!
I'm reading the worked example in Clavel et al (2015), appendix 2. In page 4, mvSIM is fed 3 parameter vectors: a matrix alpha, a matrix sigma and vector theta. I haven't been able to find the meaning of those parameters, and there's no alpha, sigma or theta in the OU equation in the main manuscript (in eq. 5, OU is written using A, beta and R...). Looking at the code, theta seems to be the root phenotype (for all traits). Is sigma a covariance matrix of traits, and alpha a covariance matrix for the optima in the OU process?
thank you in advance for your help 🙏 
(ping @katjaq)

* Edit: from p9 in appendix 2 I got that sigma is indeed covariance among traits. Still missing the meaning of the alpha matrix, though.

**Comment by JClavel** [comment]
Dear Roberto,

Thank you for your message. Indeed, there’s some mismatches (after trying to homogenise things with other implementations of the OU process – I should maybe make it clear in future releases or on the tutorial) and there’s probably a typo in the 2015 paper (see instead https://github.com/JClavel/mvMORPH/blob/master/vignettes/Computational_details.pdf).

-	“alpha” is A in eq. S4 of the link above
-	“sigma” is R (i.e. Sigma%*%t(Sigma) where Sigma is -without loss of generality – lower triangular
-	“theta” is beta…

R (sigma in the function) is the covariance matrix of the scatter generator (the Brownian part), A (alpha in the function) is not a covariance matrix (can be non-symmetric!) but rather a matrix of coefficients controlling the strength of the reversion toward the optimum between traits (it is called the drift or pull matrix). In multivariate space, the eigen-directions of the A matrix describe the direction path toward the optima. The covariance of the process (or the traits under the process) is given by a combination of A and R. When the process is stationary, this covariance is given by the function “stationary” (see eq. S18); otherwise, the covariance can be obtained from the equations S8-S13. The “stationary” covariance can be a good way to summarize the relationships between the variables (e.g. to compare evolutionary correlations with the R matrix ("sigma" in mvBM) of the BM process for instance).

Regards,

Julien

**Comment by r03ert0** [comment]
a late thank you @JClavel!
